// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_SettingCell = NULL;
lv_obj_t * ui_SettingCell1 = NULL;
lv_obj_t * ui_SettingCell2 = NULL;
lv_obj_t * ui_SettingCell3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 360);
    lv_obj_set_height(ui_Container4, 300);
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, 29);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingCell = ui_SettingCell_create(ui_Container4);
    lv_obj_set_x(ui_SettingCell, 0);
    lv_obj_set_y(ui_SettingCell, -98);

    lv_image_set_src(ui_comp_get_child(ui_SettingCell, UI_COMP_SETTINGCELL_ICON), &ui_img_wlan_png);

    lv_label_set_text(ui_comp_get_child(ui_SettingCell, UI_COMP_SETTINGCELL_NAME), "Wlan");

    lv_image_set_src(ui_comp_get_child(ui_SettingCell, UI_COMP_SETTINGCELL_ARROW), &ui_img_right_arrow_png);

    ui_SettingCell1 = ui_SettingCell_create(ui_Container4);
    lv_obj_set_x(ui_SettingCell1, -7);
    lv_obj_set_y(ui_SettingCell1, -97);

    lv_image_set_src(ui_comp_get_child(ui_SettingCell1, UI_COMP_SETTINGCELL_ICON), &ui_img_sound_png);

    lv_label_set_text(ui_comp_get_child(ui_SettingCell1, UI_COMP_SETTINGCELL_NAME), "Sound");

    ui_SettingCell2 = ui_SettingCell_create(ui_Container4);
    lv_obj_set_x(ui_SettingCell2, -7);
    lv_obj_set_y(ui_SettingCell2, -97);

    lv_image_set_src(ui_comp_get_child(ui_SettingCell2, UI_COMP_SETTINGCELL_ICON), &ui_img_brightness_png);

    lv_label_set_text(ui_comp_get_child(ui_SettingCell2, UI_COMP_SETTINGCELL_NAME), "Brightness");

    ui_SettingCell3 = ui_SettingCell_create(ui_Container4);
    lv_obj_set_x(ui_SettingCell3, -7);
    lv_obj_set_y(ui_SettingCell3, -97);

    lv_image_set_src(ui_comp_get_child(ui_SettingCell3, UI_COMP_SETTINGCELL_ICON), &ui_img_info_png);

    lv_label_set_text(ui_comp_get_child(ui_SettingCell3, UI_COMP_SETTINGCELL_NAME), "Info");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container4 = NULL;
    ui_SettingCell = NULL;
    ui_SettingCell1 = NULL;
    ui_SettingCell2 = NULL;
    ui_SettingCell3 = NULL;

}
